# Generated by Django 5.2.9 on 2025-12-05 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ects', models.FloatField()),
                ('semester', models.IntegerField()),
                ('kind', models.CharField(choices=[("обов'язкова", "Обов'язкова"), ('вибіркова', 'Вибіркова')], max_length=20)),
                ('block', models.CharField(choices=[('загальна', 'Загальна'), ('професійна', 'Професійна'), ('вільний вибір', 'Вільний вибір')], max_length=20)),
                ('req_math', models.IntegerField(default=0)),
                ('req_prog', models.IntegerField(default=0)),
                ('req_ai', models.IntegerField(default=0)),
                ('req_soft', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('prerequisites', models.ManyToManyField(blank=True, to='recommender.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('math_level', models.FloatField(default=0.0)),
                ('prog_level', models.FloatField(default=0.0)),
                ('ai_level', models.FloatField(default=0.0)),
                ('soft_level', models.FloatField(default=0.0)),
                ('interests', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommender.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Завершено'), ('in_progress', 'В процесі')], default='completed', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='recommender.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
