# Generated by Django 5.2.9 on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0002_create_default_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourseenrollment",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]

